#2.2 Librerias de Numpy e Scipy


*   2.2.1 Introducción a numpy e Scipy
*   2.2.2 Indexado con booleanos
* 2.2.3 Operaciones matematicas con numpy
* 2.2.4 Diferencias entre Arrays y listas
* 2.2.5 Ejemplo Scipy


##2.2.1 Introducción a Numpy e Scipy

Numpy es una libreria de python muy utilizada para computacion cientifica con python. En general para los que hayan trabajado con matlab tiene un comportamiento parecido a como matlab trata los arrays. Además se dará un pequeño ejemplo de scipy la cual usando numpy como vase aplica una gran variedad de algoritmos matematicos. 


In [ ]:
#importamos numpy
import numpy as np

# creamos un vector (1,2,3) que para numpy es un array (1,3)
a = np.array([1, 2, 3])
# Shape es un comando muy interesante que permite ver las dimensiones de las arrays
print(a.shape)
# para cambiar un valor del array solamente hay que acceder al indice correspondiente
a[0] = 5 
print(a)

# Ahora vamos a ver como tratar matrices en vez de vectores

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# vamos a ver que dimensiones tiene esta matriz
print (a.shape)

# Ahora vamos a mostrar como acceder filas y columnas del array
row_r1 = a[1, :]
print(row_r1, row_r1.shape)
col_r1 = a[:, 1]
print(col_r1, col_r1.shape)

(3,)
[5 2 3]
(3, 4)
[5 6 7 8] (4,)
[ 2  6 10] (3,)


## 2.2.2 Indexado con booleanos:

Un tema muy interesante y que se expandirá en el capitulo siguiente es el indexado. Aunque sea muy interesante no vamos a entrar mucho en esto ya que PANDAS (otra librería de python) tambien lo usa y es más sencillo, pero vamos a ver como hacer boolean indexing ya que es muy visual y muestra la potencia real de python que vamos a ver mas adelante. 
    

In [ ]:
# Creamos una matriz ejemplo
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print(bool_idx)  
# Imprimir "[[False False]
#          [ True  True]
#          [ True  True]]"

# recibimos una matriz con todos los elementos los cuales sean mayores que 2
# ademas si se introduce esta matriz como indice en la matriz a, solo nos va a mostrar los elementos que tienen "True"
print(a[bool_idx])
# podemos hacerlo todo en un paso de la siguiente forma (sin tener que crear bool_idx intermedia)
print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


En general las mejoras que ofrece este tipo de indexado a nuestros codigos es la siguiente:
    1. Código mas visual 
    2. Uso reducido de FOR e IF
    3. Menor fuente de bugs
    4. Mas rapido en ejecución

##2.2.3 Operaciones matematicas con numpy:

Ahora vamos a ver algunas de las posibles operaciones matematicas que incorpora numpy. Como es de esperar incluye sumas restas, transposiciones etc.

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x + y)
print(np.add(x, y))
print(x - y)
print(np.subtract(x, y))
print(x * y)
print(np.multiply(x, y))

# es importante chequear en la documentación los distintos metodos y sus opciones. Vamos a ver un ejemplo:

x = np.array([[1,2],[3,4]])
print(np.sum(x)) 
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

# las tres "sumas" dan resultados diferentes. Una es suma de todos los elementos
# otra es suma de cada columna y la ultima es suma de cada fila

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
10
[4 6]
[3 7]


2.2.4 Diferencias entre Arrays y listas

¿Que diferencia hay entre las listas y las arrays de numpy?
En general esta pregunta es de alto nivel pero vamos a intentar simplificarla lo maximo posible:
    
    1. Las listas permiten aglutinar elementos con distintos tipos de datos
    2. Las las arrays tienen que tener tipos de datos homogeneos
    3. Las arrays de numpy ocupan menos espacio en memoria que las listas
    4. Debido a como se asigna memoria en listas en arrays, las arrays son mas rapidas y permiten la vectorización de operaciones
    5. El array de numpy tiene herramientas especificas para calculo matricial
  

Despues de esto y como norma general la conclusión es que vamos a querer utizar arrays de numpy para alto volumen de datos y operaciones matematicas. Si tienes interés y quieres ver más en detalle estas diferencias aquí se explica:

https://webcourses.ucf.edu/courses/1249560/pages/python-lists-vs-numpy-arrays-what-is-the-difference 

## 2.2.5 Introducción a Scipy:

Despues de ver numpy quizas te hayas quedado un poco frio, realmente numpy es una herramienta base para muchas librerías de python que se basan en algoritmos matematicos aplicados. Así pues una de ellas muy utilizada en ambientes ingenieriles es Scipy. No se puede enseñar especificamente Scipy ya que más bien es una caja de herramientras algoritmicas que tienen distintos metodos con distintos argumentos y muy variados usos así pues la mejor forma de verlo es con un ejemplo. 

Vamos a claucular la distancia euclidea entre sets de puntos que almacenaremos en la variable "x":

In [ ]:
# Importamos los modulos relacionados los cuales se puede consultar en la documentacion
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html 

from scipy.spatial.distance import pdist, squareform
# puntos elegidos
x = np.array([[0, 1], [1, 0], [2, 0]])
print(x)
# d entonces va a ser las distancias euclideas entre estos puntos
d = squareform(pdist(x, 'euclidean'))
print(d)

[[0 1]
 [1 0]
 [2 0]]
[[0.         1.41421356 2.23606798]
 [1.41421356 0.         1.        ]
 [2.23606798 1.         0.        ]]


Más que entrar en detalle como funciona este método lo que se quiere mostrar es que existe Scipy cuenta con muchas herramientas muy utilizadas en ingenieria como : regresion multivariable, cambio de ejes de coordenadas, optimización de funciones, calculo simbolico, resolución de ecuaciones, interpolaciones, transformadas de fourier y un largo etcetera.

Así pues y comor recordatorio Scipy no es algo que se "aprende" es algo que hay que saber que existe, se consulta y si puede ayudarte en alguna tarea es cuando se aprende a utilizar el paquete en concreto.

## EJERCICIOS PARA PONER EN EDUALTRAN

https://www.w3resource.com/python-exercises/numpy/index.php

https://github.com/rougier/numpy-100 